# general/system params
seed: 0
n_jobs: 8
gpu_enabled: False
plt_color: 'white'

data_path: '../../input/manulife-retention/Worksheet in Case preparation for interview- Data Scientist v2 (002) R.xlsx'
analysis_date: '2023-03-01'




