# general/system params
seed: 0
n_jobs: 8
gpu_enabled: False
plt_color: 'white'

data_path: '../../input/manulife-retention/Worksheet in Case preparation for interview- Data Scientist v2 (002) R.xlsx'
analysis_date: '2023-03-01'
n_fold: 5
hp_tune_timeout: 10

lgbm_var_params:
  max_depth: 32
  num_leaves: 32
  subsample: 0.65
  colsample_bytree: 0.6
  reg_alpha: 1.5
  reg_lambda: 1.5

lgbm_fixed_params:
  boosting_type: 'gbdt'
  objective: 'binary'
  n_estimators: 5000
  n_jobs: -1
  random_state: 0
  learning_rate: 0.05

lgbm_fit_params:
  verbose: True
  eval_metric: 'binary_logloss'
  early_stopping_rounds: 20




